In [14]:
import numpy as np
import pandas as pd


train = pd.read_csv("Data/train.csv")
print(train)

       label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0
1          0       0       0       0       0       0       0       0       0
2          1       0       0       0       0       0       0       0       0
3          4       0       0       0       0       0       0       0       0
4          0       0       0       0       0       0       0       0       0
5          0       0       0       0       0       0       0       0       0
6          7       0       0       0       0       0       0       0       0
7          3       0       0       0       0       0       0       0       0
8          5       0       0       0       0       0       0       0       0
9          3       0       0       0       0       0       0       0       0
10         8       0       0       0       0       0       0       0       0
11         9       0       0       0       0       0       0       0       0
12         1       0       0       0       0       0       0       0       0
13         3       0       0       0       0       0       0       0       0
14         3       0       0       0       0       0       0       0       0
15         1       0       0       0       0       0       0       0       0
16         2       0       0       0       0       0       0       0       0
17         0       0       0       0       0       0       0       0       0
18         7       0       0       0       0       0       0       0       0
19         5       0       0       0       0       0       0       0       0
20         8       0       0       0       0       0       0       0       0
21         6       0       0       0       0       0       0       0       0
22         2       0       0       0       0       0       0       0       0
23         0       0       0       0       0       0       0       0       0
24         2       0       0       0       0       0       0       0       0
25         3       0       0       0       0       0       0       0       0
26         6       0       0       0       0       0       0       0       0
27         9       0       0       0       0       0       0       0       0
28         9       0       0       0       0       0       0       0       0
29         7       0       0       0       0       0       0       0       0
...      ...     ...     ...     ...     ...     ...     ...     ...     ...
41970      2       0       0       0       0       0       0       0       0
41971      3       0       0       0       0       0       0       0       0
41972      4       0       0       0       0       0       0       0       0
41973      4       0       0       0       0       0       0       0       0
41974      3       0       0       0       0       0       0       0       0
41975      9       0       0       0       0       0       0       0       0
41976      2       0       0       0       0       0       0       0       0
41977      4       0       0       0       0       0       0       0       0
41978      4       0       0       0       0       0       0       0       0
41979      4       0       0       0       0       0       0       0       0
41980      7       0       0       0       0       0       0       0       0
41981      2       0       0       0       0       0       0       0       0
41982      8       0       0       0       0       0       0       0       0
41983      7       0       0       0       0       0       0       0       0
41984      3       0       0       0       0       0       0       0       0
41985      3       0       0       0       0       0       0       0       0
41986      0       0       0       0       0       0       0       0       0
41987      5       0       0       0       0       0       0       0       0
41988      0       0       0       0       0       0       0       0       0
41989      5       0       0       0       0       0       0       0       0
41990      3       0       0       0       0       0       0       0       0
41991      1       0       0       0       0       0       0       0       0
41992      9       0       0       0       0       0       0       0       0
41993      6       0       0       0       0       0       0       0       0
41994      4       0       0       0       0       0       0       0       0
41995      0       0       0       0       0       0       0       0       0
41996      1       0       0       0       0       0       0       0       0
41997      7       0       0       0       0       0       0       0       0
41998      6       0       0       0       0       0       0       0       0
41999      9       0       0       0       0       0       0       0       0

       pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0    ...            0         0         0         0         0
1           0    ...            0         0         0         0         0
2           0    ...            0         0         0         0         0
3           0    ...            0         0         0         0         0
4           0    ...            0         0         0         0         0
5           0    ...            0         0         0         0         0
6           0    ...            0         0         0         0         0
7           0    ...            0         0         0         0         0
8           0    ...            0         0         0         0         0
9           0    ...            0         0         0         0         0
10          0    ...            0         0         0         0         0
11          0    ...            0         0         0         0         0
12          0    ...            0         0         0         0         0
13          0    ...            0         0         0         0         0
14          0    ...            0         0         0         0         0
15          0    ...            0         0         0         0         0
16          0    ...            0         0         0         0         0
17          0    ...            0         0         0         0         0
18          0    ...            0         0         0         0         0
19          0    ...            0         0         0         0         0
20          0    ...            0         0         0         0         0
21          0    ...            0         0         0         0         0
22          0    ...            0         0         0         0         0
23          0    ...            0         0         0         0         0
24          0    ...            0         0         0         0         0
25          0    ...            0         0         0         0         0
26          0    ...            0         0         0         0         0
27          0    ...            0         0         0         0         0
28          0    ...            0         0         0         0         0
29          0    ...            0         0         0         0         0
...       ...    ...          ...       ...       ...       ...       ...
41970       0    ...            0         0         0         0         0
41971       0    ...            0         0         0         0         0
41972       0    ...            0         0         0         0         0
41973       0    ...            0         0         0         0         0
41974       0    ...            0         0         0         0         0
41975       0    ...            0         0         0         0         0
41976       0    ...            0         0         0         0         0
41977       0    ...            0         0         0         0         0
41978       0    ...            0         0         0         0         0
41979       0    ...            0         0         0         0         0
41980       0    ...           27       253       110         0         0
41981       0    ...            0         0         0         0         0
41982       0    ...            0         0         0         0         0
41983       0    ...            0         0         0         0         0
41984       0    ...            0         0         0         0         0
41985       0    ...            0         0         0         0         0
41986       0    ...            0         0         0         0         0
41987       0    ...            0         0         0         0         0
41988       0    ...            0         0         0         0         0
41989       0    ...            0         0         0         0         0
41990       0    ...            0         0         0         0         0
41991       0    ...            0         0         0         0         0
41992       0    ...            0         0         0         0         0
41993       0    ...            0         0         0         0         0
41994       0    ...            0         0         0         0         0
41995       0    ...            0         0         0         0         0
41996       0    ...            0         0         0         0         0
41997       0    ...            0         0         0         0         0
41998       0    ...            0         0         0         0         0
41999       0    ...            0         0         0         0         0

       pixel779  pixel780  pixel781  pixel782  pixel783
0             0         0         0         0         0
1             0         0         0         0         0
2             0         0         0         0         0
3             0         0         0         0         0
4             0         0         0         0         0
5             0         0         0         0         0
6             0         0         0         0         0
7             0         0         0         0         0
8             0         0         0         0         0
9             0         0         0         0         0
10            0         0         0         0         0
11            0         0         0         0         0
12            0         0         0         0         0
13            0         0         0         0         0
14            0         0         0         0         0
15            0         0         0         0         0
16            0         0         0         0         0
17            0         0         0         0         0
18            0         0         0         0         0
19            0         0         0         0         0
20            0         0         0         0         0
21            0         0         0         0         0
22            0         0         0         0         0
23            0         0         0         0         0
24            0         0         0         0         0
25            0         0         0         0         0
26            0         0         0         0         0
27            0         0         0         0         0
28            0         0         0         0         0
29            0         0         0         0         0
...         ...       ...       ...       ...       ...
41970         0         0         0         0         0
41971         0         0         0         0         0
41972         0         0         0         0         0
41973         0         0         0         0         0
41974         0         0         0         0         0
41975         0         0         0         0         0
41976         0         0         0         0         0
41977         0         0         0         0         0
41978         0         0         0         0         0
41979         0         0         0         0         0
41980         0         0         0         0         0
41981         0         0         0         0         0
41982         0         0         0         0         0
41983         0         0         0         0         0
41984         0         0         0         0         0
41985         0         0         0         0         0
41986         0         0         0         0         0
41987         0         0         0         0         0
41988         0         0         0         0         0
41989         0         0         0         0         0
41990         0         0         0         0         0
41991         0         0         0         0         0
41992         0         0         0         0         0
41993         0         0         0         0         0
41994         0         0         0         0         0
41995         0         0         0         0         0
41996         0         0         0         0         0
41997         0         0         0         0         0
41998         0         0         0         0         0
41999         0         0         0         0         0

[42000 rows x 785 columns]

In [16]:
X = train.loc[:, train.columns != 'label']
Y = train.loc[:, train.columns == 'label']
X = X.as_matrix()
Y = Y.as_matrix()
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30, random_state=42)

In [17]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(29400, 784) (12600, 784) (29400, 1) (12600, 1)

In [24]:
z = pd.DataFrame(X_train)
z['label'] = y_train
z = z.set_index('label').reset_index()

In [25]:
z.to_csv("Data/training.csv")

In [66]:
zt = pd.DataFrame(X_test)
zt2 = pd.DataFrame(y_test)
zt3 = zt2.sample(frac=1)
zt3.reset_index(inplace=True)
zt3.drop("index",axis=1,inplace=True)
zt3 = zt3.rename(index=str, columns={0: "label"})
zt2 = zt2.rename(index=str, columns={0: "label"})

       label
0          8
1          1
2          9
3          9
4          8
5          6
6          2
7          2
8          7
9          1
10         6
11         3
12         1
13         2
14         7
15         4
16         3
17         3
18         6
19         4
20         9
21         5
22         2
23         6
24         0
25         0
26         0
27         8
28         6
29         3
...      ...
12570      6
12571      0
12572      3
12573      1
12574      2
12575      3
12576      0
12577      9
12578      6
12579      3
12580      5
12581      3
12582      2
12583      6
12584      3
12585      4
12586      2
12587      3
12588      6
12589      2
12590      2
12591      0
12592      0
12593      4
12594      7
12595      0
12596      3
12597      5
12598      5
12599      0

[12600 rows x 1 columns]

In [67]:
zt3.to_csv("Data/submission.csv")

In [68]:
zt2.to_csv("Data/answers.csv")

In [69]:
zt.to_csv("Data/testing.csv")